### ISSUE TITLE
Begin in de single column

### ISSUE THREAD

**Issue by joostf** [Ramon96/99verhalen#1]
... en bouw dan op naar grotere contexten

**Comment by Ramon96** [comment]
De mobiele viewport heb ik single column gemaakt, ik ga vanuit het mobiele viewport verder werken. ik heb de contexten die ik momenteel heb gemaakt in een media query gestopt zodat ik dat verder kan uitwerken zodra de tijd rijp is.

Mobile First, desktop second.
Lets make mobile great again!
